### ISSUE TITLE
Incorrect Examples

### ISSUE THREAD

**Issue by andrew-knack** [kanga333/variable-mapper#10]
Hi there, love the GitHub action but there seems to be some mistakes with the examples in the readme. 

When I tried `uses: kanga333/variable-mapper@v1` I got the error: 
`An action could not be found at the URI 'https://api.github.com/repos/kanga333/variable-mapper/tarball/v1'`.
The fix for this is to change it to replace it with `uses: kanga333/variable-mapper@v0.1.0`.

The second problem is with secrets the readme has `"AWS_ACCESS_KEY_ID": ${{ secrets.PROD_AWS_ACCESS_KEY_ID }},`.
This fails for me with `Unexpected token A in JSON at position 77` quoting the secret fixes this.

**Comment by kanga333** [comment]
Thanks for your report ! I fixed the problem and made sure to test the examples correctly.
