### ISSUE TITLE
GitHub Action's deprecation warnings regarding Node.js 12

### ISSUE THREAD

**Issue by oblivioncth** [kanga333/variable-mapper#101]
Possible you're already aware of this, but just letting you know that running this action now produces the following warning:
````
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: kanga333/variable-mapper
````

**Comment by kanga333** [comment]
Thank you for the notice. I'll update this action this week.

**Comment by kanga333** [comment]
@oblivioncth 
I've updated the version of `Node.js` by #103.
Could you try `kanga333/variable-mapper@v0.3.0`?

**Comment by oblivioncth** [comment]
Sorry, forgot to get back to you on this.

v0.3.0 seems to work fine, and of course does not produce the warning
