### ISSUE TITLE
Error: Unexpected token *** in JSON

### ISSUE THREAD

**Issue by gaspardip** [kanga333/variable-mapper#105]
In my `deploy-preview.yml` workflow I have the following.

```
      - uses: kanga333/variable-mapper@master
        with:
          key: "${{github.base_ref}}"
          map: |
            {
              "master": {
                "VITE_ENVIRONMENT": "production",
              },
              "develop": {
                "VITE_ENVIRONMENT": "staging",
              },
              ".*": {
                "VITE_ENVIRONMENT": "development",
              }
            }
```

It recently started failing with the following error (extract from the logs):

```
2022-11-01T10:40:32.2086812Z ##[group]Run kanga333/variable-mapper@master
2022-11-01T10:40:32.2087407Z with:
2022-11-01T10:40:32.2087777Z   key: develop
2022-11-01T10:40:32.2088981Z   map: ***
  "master": ***
    "VITE_ENVIRONMENT": "production",
  ***,
  "develop": ***
    "VITE_ENVIRONMENT": "staging",
  ***,
  ".*": ***
    "VITE_ENVIRONMENT": "development",
  ***
***

2022-11-01T10:40:32.2090045Z   export_to: log,env
2022-11-01T10:40:32.2090430Z   mode: first_match
2022-11-01T10:40:32.2090790Z env:
2022-11-01T10:40:32.2091175Z   BRANCH: feature/new-graph-segment
2022-11-01T10:40:32.2091595Z ##[endgroup]
2022-11-01T10:40:32.2941053Z ##[error]Unexpected token *** in JSON at position 102
```

The workflow was previously working with this exact same setup so I'm not sure if the new version introduced some bug or I'm at fault somehow here.

**Comment by gaspardip** [comment]
It seems [this](https://stackoverflow.com/questions/72173464/why-does-github-action-log-show-asterisk) is related somehow.

**Comment by kanga333** [comment]
@gaspardip Thank you for the report!
It seems the problem that the map argument is invalid JSON string.

This argument is invalid JSON.

```
map: |
  {
    "master": {
      "VITE_ENVIRONMENT": "production",
    },
    "develop": {
      "VITE_ENVIRONMENT": "staging",
    },
    ".*": {
      "VITE_ENVIRONMENT": "development",
    }
  }
```

If you fix like this, it works.

```
map: |
  {
    "master": {
      "VITE_ENVIRONMENT": "production"
    },
    "develop": {
      "VITE_ENVIRONMENT": "staging"
    },
    ".*": {
      "VITE_ENVIRONMENT": "development"
    }
  }
```

I tested it on https://github.com/kanga333/github-playgruond/pull/9.

**Comment by gaspardip** [comment]
Sorry, yes I did have a dangling comma there but the error I was referring to with this issue is [this one](https://github.com/actions/runner/issues/995). Basically, I had a multiline JSON secret and the Github runner was masking `{` and `}` as `***`. The solution was to both remove the comma and put the secret as one-liner (remove spaces, new lines, etc) in Github.

Thank you!
