### ISSUE TITLE
Don't stop on first match

### ISSUE THREAD

**Issue by ogizanagi** [kanga333/variable-mapper#14]
Hi 👋 

I have a use-case where I'd like to configure everything in a single step by not stopping on first match. I.e, given:

```json
{
  "*@production": {
    "DEPLOY_CONFIG_BRANCH": "master",
    "SSH_SECRET_KEY": "SSH_DEPLOY_KEY_PRODUCTION"
  },
  "api@production": {
    "DEPLOY_ENVIRONMENT_URL": "https://api.example.com"
  },
  "admin@production": {
    "DEPLOY_ENVIRONMENT_URL": "https://admin.example.com"
  },
  "*@staging": {
    "DEPLOY_CONFIG_BRANCH": "staging",
    "SSH_SECRET_KEY": "SSH_DEPLOY_KEY_STAGING"
  },
  "api@staging": {
    "DEPLOY_ENVIRONMENT_URL": "https://api.staging.example.com"
  },
  "admin@staging": {
    "DEPLOY_ENVIRONMENT_URL": "https://admin.staging.example.com"
  }
}
```

if the key is `api@staging`, I'd like it to match both `*@staging` and `api@staging`, so the three `DEPLOY_CONFIG_BRANCH`, `SSH_SECRET_KEY`, `DEPLOY_ENVIRONMENT_URL` would be set.

Order might matter in this case, as an env var declared in a first matching key might be overridden by the next one. We should just choose either it overrides or ignores an already set env var in such cases and document the behavior.

**Comment by kanga333** [comment]
Thanks for the use case request.
We would like to support more flexible setting of environment variables. We need the option to control the matching of environment variables.

```
mode: Option to control environment variable matching.

- first_match: Current behavior. (Default)
- overwrite: Match from top to bottom. Duplicate keys are overwritten.
- fill: Match from top to bottom. Duplicate keys will be ignored. Unduplicated keys are set to a new key.
```

I'm planning to tackle this issue over the weekend.

**Comment by kanga333** [comment]
@ogizanagi Hi! I implemented the mode option to support use-cases other than first_match. In your use-case, I think you should be able to use `overwrite ` or `fill`. It is available in `v0.2.0`. For more information on how to use it, please refer to the following documents. Thank you.
https://github.com/kanga333/variable-mapper#switching-the-behavior-of-getting-the-variable

**Comment by ogizanagi** [comment]
Hey @kanga333 , that's great news! Thanks. I'll give it a try tomorrow :)

**Comment by ogizanagi** [comment]
Sorry for the lack of feedback, I totally forgotten to try this until now. Thanks for implementing this feature 👍🏻
