### ISSUE TITLE
what needs to be done if the value of the key is another json object

### ISSUE THREAD

**Issue by alexgocariq** [kanga333/variable-mapper#95]
your action is very useful, but in my case i have json value which I need to add into your json object and I have error, obviously my value causing in issue. what will be your advise?

**Comment by kanga333** [comment]
@alexgocariq Thank you reporting.

Is this the issue that you are facing? 
https://github.com/kenju/github-actions-artillery/issues/3

I think your `"${{ secrets.GCP_SA_GHA_DEVNONPCI_TERRAFORM}}"` contains invalid characters as JSON string like double quote.  I recommend you to try using `toJSON` function that escape invalid characters. 

For example.

```
steps:
  - uses: kanga333/variable-mapper@master
    with:
      key: "${{ env.PROJECT_ID }}"
      map: |
        {
          "testing": {
            "gcpSa": ${{ toJSON(secrets.GCP_SA_GHA_DEVNONPCI_TERRAFORM) }}
          }
        }
```

Note: You don't need to enclose `toJSON` values. This function return enclosed value.

**Comment by alexgocariq** [comment]
Your action is very useful, I was working on a similar concept but then I
found yours, I will use yours for now, looks like it should cover my cases,
and I like the fact that you used regular expressions for matching. It
gives us flexibility
Yes thank you so much, if I will be in my java ide there will not be a
problem, thanks for your suggestion.

Regards,
Alexander
